mono/mono/Areas/Auction/Controllers/ItemController.cs
using Mono.Areas.Auction.Models;
using Mono.Data;
using Mono.Model;
using Mono.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Data;

namespace Mono.Areas.Auction.Controllers
{
    [Authorize(Roles = "user")]
    public class ItemController : Controller
    {       
        private IUnitOfWork unitOfWork;

        public ItemController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        //
        // GET: /Auction/Item/
        public ActionResult Index(int? id)
        {
            ItemViewModel itemViewModel;

            if (id == null)
            {
                var subCategories = unitOfWork.CategoryRepository.Get(filter: c => c.ParentCategoryID == null, orderBy: q => q.OrderBy(c => c.Name), includeProperties: "Food");

                itemViewModel = AddCategoryFood("All", null, subCategories, new List<Food>());
            }
            else
            {
                Category category = unitOfWork.CategoryRepository.GetByID(id);

                if (category == null)
                    return HttpNotFound();

                var subCategories = category.ChildCategory.OrderBy(c => c.Name).ToList();
                var foods = category.Food.OrderBy(f => f.Name).ToList();

                itemViewModel = AddCategoryFood(category.Name, category.ParentCategoryID, subCategories, foods);
            }
            
            if(Request.IsAjaxRequest())
            {
                return PartialView("_Category", itemViewModel);
            }

            return View("Index", itemViewModel);
        }

        //
        // GET: /Auction/Add/
        public ActionResult Add(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Food food = unitOfWork.FoodRepository.GetByID(id);

            if (food == null)
            {
                return HttpNotFound();
            }

            Category category = unitOfWork.CategoryRepository.GetByID(food.CategoryID);
            ViewBag.CategorySizeID = new SelectList(unitOfWork.CategorySizeRepository.SizeValues(category.SizeType), "ID", "Value");
            ViewBag.IngredientsList = new MultiSelectList(unitOfWork.IngredientRepository.IngredientsForFood(food), "ID", "Name");

            FoodIngredientViewModel foodIngredientViewModel = new FoodIngredientViewModel();
            foodIngredientViewModel.FoodID = (int)id;
            foodIngredientViewModel.FoodName = food.Name;
            foodIngredientViewModel.Pieces = 1;

            return View("Add", foodIngredientViewModel);
        }

        // POST: /Auction/Item/Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(FoodIngredientViewModel foodIngredientViewModel)
        {
            if (foodIngredientViewModel.FoodID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var food = unitOfWork.FoodRepository.GetByID(foodIngredientViewModel.FoodID);

            if (food == null)
            {
                return HttpNotFound();
            }

            try 
            { 
                if (ModelState.IsValid)
                {
                    FoodIngredient foodIngredient = new FoodIngredient();

                    foodIngredient.UserID = User.Identity.GetUserId();
                    foodIngredient.FoodID = (int)foodIngredientViewModel.FoodID;
                    foodIngredient.Description = foodIngredientViewModel.Description;
                    foodIngredient.CategorySizeID = foodIngredientViewModel.CategorySizeID;
                    foodIngredient.Pieces = foodIngredientViewModel.Pieces;

                    foodIngredient.Ingredients = new List<Ingredient>();

                    if (foodIngredientViewModel.Ingredients != null)
                        foreach (string stringId in foodIngredientViewModel.Ingredients)
                        {
                            int id;
                    
                            if (Int32.TryParse(stringId, out id))
                            {
                                Ingredient ingredient = unitOfWork.IngredientRepository.GetByID(id);

                                if (ingredient != null)
                                {
                                    foodIngredient.Ingredients.Add(ingredient);
                                }
                            }
                        }

                    unitOfWork.FoodIngredientRepository.Insert(foodIngredient);
                    unitOfWork.Save();

                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name after DataException and add a line here to write a log.
                ModelState.AddModelError(string.Empty, "Unable to save changes. Try again, and if the problem persists contact your system administrator.");
            }

            Category category = unitOfWork.CategoryRepository.GetByID(food.CategoryID);

            ViewBag.CategorySizeID = new SelectList(unitOfWork.CategorySizeRepository.SizeValues(category.SizeType), "ID", "Value");
            ViewBag.IngredientsList = new MultiSelectList(unitOfWork.IngredientRepository.IngredientsForFood(food), "ID", "Name");

            return View("Add", foodIngredientViewModel);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }

        #region HelperFunctions

        private ItemViewModel AddCategoryFood(String name, int? parentCategoryID, IEnumerable<Category> subCategories, IEnumerable<Food> foods)
        {
            ItemViewModel itemViewModel = new ItemViewModel
            {
                Name = name,
                ParentCategoryID = parentCategoryID,
                ListCategoryFood = new List<ListCategoryFoodItem>()
            };

            foreach (var subcategory in subCategories)
            {
                ListCategoryFoodItem listCategoryFoodItem = new ListCategoryFoodItem
                {
                    Name = subcategory.Name,
                    ItemID = subcategory.ID,
                    PhotoID = subcategory.PhotoID,
                    Type = ListCategoryFoodItemType.Category
                };
                itemViewModel.ListCategoryFood.Add(listCategoryFoodItem);
            }

            foreach (var food in foods)
            {
                ListCategoryFoodItem listCategoryFoodItem = new ListCategoryFoodItem
                {
                    Name = food.Name,
                    ItemID = food.ID,
                    PhotoID = food.PhotoID,
                    Type = ListCategoryFoodItemType.Food
                };
                itemViewModel.ListCategoryFood.Add(listCategoryFoodItem);
            }

            return itemViewModel;
        }

        #endregion
    }
}

mono/mono/Areas/Auction/Controllers/OfferController.cs
using Mono.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Mono.Model;
using System.Data;
using System.Net;

namespace Mono.Areas.Auction.Controllers
{
    [Authorize(Roles = "restaurant")]
    public class OfferController : Controller
    {
        private IUnitOfWork unitOfWork;

        public OfferController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        //
        // GET: /Auction/Offer/
        public ActionResult Index()
        {
            var restaurantID = unitOfWork.UserRepository.GetByID(User.Identity.GetUserId()).RestaurantID;
            var offers = unitOfWork.OfferRepository.Get(o => o.RestaurantID == restaurantID, q => q.OrderByDescending(o => o.DateTime)).ToList();
            return View("Index", offers);
        }

        // GET: /Auction/Offer/orders
        public ActionResult Orders()
        {
            var orders = unitOfWork.OrderRepository.Get(o => o.Status == Mono.Model.Status.Active, q => q.OrderByDescending(o => o.DateTime)).ToList();
            return View("Orders", orders);
        }

        public ActionResult Order(int id)
        {
            if (Request.IsAjaxRequest())
            {
                var order = unitOfWork.OrderRepository.GetByID(id);
                return PartialView("_Order", order);
            }
            else
                return RedirectToAction("Orders"); 
        }

        public int OrdersCount()
        {
            return unitOfWork.OrderRepository.Get(o => o.Status == Mono.Model.Status.Active, q => q.OrderByDescending(o => o.DateTime)).Count();
        }

        //
        // GET: /Auction/Offer/Details
        public ActionResult Details(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest); 
            }
            var order = unitOfWork.OrderRepository.GetByID(id);
            if (order == null)
            {
                return HttpNotFound();
            }

            return View("Details", order);
        }

        // GET: /Auction/Offer/MakeOffer/3
        public ActionResult MakeOffer(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest); 
            }
            var order = unitOfWork.OrderRepository.GetByID(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            if (order.Status != Status.Active)
            {
                return RedirectToAction("Orders");
            }

            ViewBag.OrderID = id;
            return View("MakeOffer");
        }

        // POST: /Auction/Offer/MakeOffer
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult MakeOffer([Bind(Include = "ID,Description,Price,DeliveryTime,OrderID")] Offer offer)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (unitOfWork.OrderRepository.GetByID(offer.OrderID).Status != Status.Active)
                    {
                        ModelState.AddModelError(string.Empty, "Order no longer active.");
                    }
                    else
                    {
                        offer.DateTime = System.DateTime.Now;
                        offer.RestaurantID = (int)unitOfWork.UserRepository.GetByID(User.Identity.GetUserId()).RestaurantID;

                        unitOfWork.OfferRepository.Insert(offer);
                        unitOfWork.Save();

                        var hubContext = Microsoft.AspNet.SignalR.GlobalHost.ConnectionManager.GetHubContext<ChatHub>();
                        hubContext.Clients.User(offer.Order.User.UserName).offersCountForOrderNew(offer.OrderID, offer.ID);

                        return RedirectToAction("Index");
                    }
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name after DataException and add a line here to write a log.
                ModelState.AddModelError(string.Empty, "Unable to save changes. Try again, and if the problem persists contact your system administrator.");
            }

            ViewBag.OrderID = offer.OrderID;
            return View("MakeOffer", offer);
        }

        // GET: /Auction/Offer/Delete/5
        public ActionResult Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Delete failed. Try again, and if the problem persists see your system administrator.";
            }
            Offer offer = unitOfWork.OfferRepository.GetByID((int)id);
            if (offer == null)
            {
                return HttpNotFound();
            }
            if (offer.RestaurantID != unitOfWork.UserRepository.GetByID(User.Identity.GetUserId()).RestaurantID || offer.ID == offer.Order.AcceptedOfferID)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View("Delete", offer);
        }

        // POST: /Auction/Offer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Offer offer = unitOfWork.OfferRepository.GetByID(id);
                if (offer.RestaurantID == unitOfWork.UserRepository.GetByID(User.Identity.GetUserId()).RestaurantID && offer.ID != offer.Order.AcceptedOfferID)
                {
                    var userName = offer.Order.User.UserName;
                    var orderID = offer.OrderID;

                    unitOfWork.OfferRepository.Delete(id);
                    unitOfWork.Save();

                    var hubContext = Microsoft.AspNet.SignalR.GlobalHost.ConnectionManager.GetHubContext<ChatHub>();
                    hubContext.Clients.User(userName).offersCountForOrderDeleted(orderID, offer.ID);

                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name after DataException and add a line here to write a log.
            }
            return RedirectToAction("Delete", new { id = id, saveChangesError = true });
        }
	}
}

mono/mono/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("admin"))
                    {
                        string v = "";
                                
                        if(ViewContext.RouteData.DataTokens["area"] == "Admin") 
                        {
                           v = "class=active";
                        }
                        
                        <li @(v) >@Html.ActionLink("Edit", "Index", "Admin", new { area = "Admin" }, null)</li>
                    }
                    @if (User.IsInRole("user"))
                    {
                        <li>@Html.ActionLink("Items",  "Index", "Item",  new { area = "Auction" }, null)</li>
                        <li><a href="@Url.Action("Index", "Order", new { area = "Auction" })">Orders <span id="offersCount" class="badge"></span></a></li>
                    }
                    @if (User.IsInRole("restaurant"))
                    {                       
                        <li><a href="@Url.Action("Orders", "Offer", new { area = "Auction" })">Orders <span id="ordersCount" class="badge"></span></a></li>
                        <li>@Html.ActionLink("Offers", "Index", "Offer", new { area = "Auction" }, null)</li>
                    }
                    <li>@Html.ActionLink("Restaurants", "Restaurants", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, null)</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Restaurant application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/signalr")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/chosen")
    @RenderSection("scripts", required: false)
    <script>
        $(function() {
            $('.chosen-select').chosen();
            $('.chosen-select-deselect').chosen({ allow_single_deselect: true });
        });
    </script>

    @if (User.IsInRole("user"))
    {
        <script src="~/signalr/hubs"></script>
        <script>
            $(function () {
                signalRFunctions.userClient();
            });
        </script>
    }

    @if (User.IsInRole("restaurant"))
    {
        <script src="~/signalr/hubs"></script>
        <script>
            $(function () {
                signalRFunctions.restaurantClient();
            });
        </script>
    }

</body>
</html>