mono/mono/Areas/Admin/Controllers/CategorySizeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mono.Model;
using Mono.Data;
using PagedList;
using System.Linq.Expressions;
using System.Data.Entity.SqlServer;
using Mono.Helper;

namespace Mono.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    public class CategorySizeController : Controller
    {
        private IUnitOfWork unitOfWork;
        public CategorySizeController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        // GET: /Admin/CategorySize/
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            int pageNumber = ControllerHelper.newSearchPageNumber(ref searchString, page, currentFilter);

            Expression<Func<CategorySize, bool>> filter = null;
            if (!String.IsNullOrEmpty(searchString))
            {
                filter = (s =>
                    SqlFunctions.StringConvert((double)s.Type).Contains(searchString.ToUpper()) ||
                    s.Value.ToUpper().Contains(searchString.ToUpper())
                );
            }

            Func<IQueryable<CategorySize>, IOrderedQueryable<CategorySize>> orderBy = null;
            switch (sortOrder)
            {
                case "Value_desc":
                    orderBy = (q => q.OrderByDescending(s => s.Value));
                    break;
                case "Type":
                    orderBy = (q => q.OrderBy(s => s.Type));
                    break;
                case "Type_desc":
                    orderBy = (q => q.OrderByDescending(s => s.Type));
                    break;
                default:
                    orderBy = (q => q.OrderBy(s => s.Value));
                    break;
            }

            var categorySizes = unitOfWork.CategorySizeRepository.Get(filter: filter, orderBy: orderBy);

            ViewBag.CurrentFilter = searchString;
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Value_desc" : "";
            ViewBag.TypeSortParm = sortOrder == "Type" ? "Type_desc" : "Type";

            return View("Index", categorySizes.ToPagedList(pageNumber, int.Parse(System.Web.Configuration.WebConfigurationManager.AppSettings["PageSize"].ToString()) ));
        }

        // GET: /Admin/CategorySize/Details/5
        public ActionResult Details(int id)
        {
            CategorySize categorySize = unitOfWork.CategorySizeRepository.GetByID(id);
            if (categorySize == null)
            {
                return HttpNotFound();
            }
            return View("Details", categorySize);
        }

        // GET: /Admin/CategorySize/Create
        public ActionResult Create()
        {
            return View("Create");
        }

        // POST: /Admin/CategorySize/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,Type,Value,Order")] CategorySize categorySize)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    unitOfWork.CategorySizeRepository.Insert(categorySize);
                    unitOfWork.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name after DataException and add a line here to write a log.
                ModelState.AddModelError(string.Empty, "Unable to save changes. Try again, and if the problem persists contact your system administrator.");
            }

            return View("Create", categorySize);
        }

        // GET: /Admin/CategorySize/Edit/5
        public ActionResult Edit(int id)
        {
            CategorySize categorySize = unitOfWork.CategorySizeRepository.GetByID(id);
            if (categorySize == null)
            {
                return HttpNotFound();
            }
            return View("Edit", categorySize);
        }

        // POST: /Admin/CategorySize/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,Type,Value,Order")] CategorySize categorySize)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    unitOfWork.CategorySizeRepository.Update(categorySize);
                    unitOfWork.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name after DataException and add a line here to write a log.
                ModelState.AddModelError(string.Empty, "Unable to save changes. Try again, and if the problem persists contact your system administrator.");
            }

            return View("Edit", categorySize);
        }

        // GET: /Admin/CategorySize/Delete/5
        public ActionResult Delete(int id, bool? saveChangesError = false)
        {
            CategorySize categorySize = unitOfWork.CategorySizeRepository.GetByID(id);
            if (categorySize == null)
            {
                return HttpNotFound();
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Delete failed. Try again, and if the problem persists see your system administrator.";
            }

            return View("Delete", categorySize);
        }

        // POST: /Admin/CategorySize/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                CategorySize categorySize = unitOfWork.CategorySizeRepository.GetByID(id);
                unitOfWork.CategorySizeRepository.Delete(id);
                unitOfWork.Save();
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name after DataException and add a line here to write a log.
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }
            return RedirectToAction("Index");
        }

        // GET: /Admin/CategorySize/Type/5
        public ActionResult Type(int id)
        {          
            if (unitOfWork.CategorySizeRepository.Get(s => s.Type == id).FirstOrDefault() == null)
            {
                return HttpNotFound();
            }

            ViewBag.SizeValuesString = unitOfWork.CategorySizeRepository.SizeValuesString((int)id);

            return View("Type");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

mono/mono/Areas/Admin/Views/CategorySize/Create.cshtml
@model Mono.Model.CategorySize

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Html.RenderPartial("_AdminMenu");
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category size</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Type, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type)
                @Html.ValidationMessageFor(model => model.Type)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value)
                @Html.ValidationMessageFor(model => model.Value)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Order, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Order)
                @Html.ValidationMessageFor(model => model.Order)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

mono/mono/Areas/Admin/Views/CategorySize/Delete.cshtml
@model Mono.Model.CategorySize

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Html.RenderPartial("_AdminMenu");
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category size</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Order)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

mono/mono/Areas/Admin/Views/CategorySize/Details.cshtml
@model Mono.Model.CategorySize

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Html.RenderPartial("_AdminMenu");
}

<h2>Details</h2>

<div>
    <h4>Category size</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Order)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

mono/mono/Areas/Admin/Views/CategorySize/Edit.cshtml
@model Mono.Model.CategorySize

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Html.RenderPartial("_AdminMenu");
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category size</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Type, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type)
                @Html.ValidationMessageFor(model => model.Type)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value)
                @Html.ValidationMessageFor(model => model.Value)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Order, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Order)
                @Html.ValidationMessageFor(model => model.Order)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

mono/mono/Areas/Admin/Views/CategorySize/Index.cshtml
@model PagedList.IPagedList<Mono.Model.CategorySize>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Html.RenderPartial("_AdminMenu");
}

<h2>Category sizes</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "CategorySize", FormMethod.Get))
{
    <p>
        Find by value or type: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Type", "Index", new { sortOrder = ViewBag.TypeSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Value", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Order
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(@item.Type.ToString(), "type/"+@item.Type.ToString())
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Value)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Order)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

mono/mono/Areas/Admin/Views/CategorySize/Type.cshtml
@{
    ViewBag.Title = "Type";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Html.RenderPartial("_AdminMenu");
}

<h2>Type</h2>
<p>@ViewBag.SizeValuesString</p>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>